version: '3.8'

services:
  app_srv:
    # hostname: ystuty_prkom_simple
    build:
      context: .
      target: base
      dockerfile: ./Dockerfile
    command: yarn start:dev
    links:
      - redis
    volumes:
      - ./.env:/home/node/app/.env
      - ./.cache-store:/home/node/app/.cache-store
    networks:
      - ystuty_network
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true # docker run -t

  redis:
    image: 'redis:alpine'
    volumes:
      - ./redis-data:/data
    networks:
      - ystuty_network

networks:
  ystuty_network:
    # name: ystuty_network
    # driver: bridge
    external:
      name: ystuty_network
